const FETCH_NEWS = {
  LOAD: "FETCH_NEWS_LOAD",
  SUCCESS: "FETCH_NEWS_SUCCESS",
  FAIL: "FETCH_NEWS_FAIL",
  CATEGORIES: "FETCH_NEWS_CATEGORIES",
};

const COUNTRY = {
  SELECT: "SELECT_COUNTRY",
};

const CATEGORY = {
  SET_ACTIVE: "SET_ACTIVE_CATEGORY",
};

const ADDITIONAL = {
  REFRESH_ARTICLES: "REFRESH_ARTICLES",
};
export { FETCH_NEWS, COUNTRY, CATEGORY, ADDITIONAL };
